### ISSUE TITLE
Browser selection option implementation

### ISSUE THREAD

**Issue by Krystus** [AllanOricil/nuxt-vscode-extension#11]
It will be perfect if we can choose default browser in the extension settings. I'm using Chrome for work, but standard every day browser is set to Safari.

**Comment by AllanOricil** [comment]
Ok. I will create a config and a selection box. If the default browser is not set, then the selection box will open with options. I just can't garantee you have the browser installed.

**Comment by AllanOricil** [comment]
Cant be done because of an api limitation
