### ISSUE TITLE
Is it possible to show the nuxt terminal during build (just as WebStorm?)

### ISSUE THREAD

**Issue by LoganTann** [AllanOricil/nuxt-vscode-extension#2]
Everything is the title

**Comment by AllanOricil** [comment]
What exactly you want to do? Send pictures showing what you want

**Comment by LoganTann** [comment]
Hello, sorry for is unclear issue... I didn't take time to ask exactly what I need.

When I click to the build button, it changes to "open app" and it opens the browser at `http://localhost:3000/`. However, we cannot see the build output. While the linter, vscode and even nuxt (in the browser) prints most build errors, the tool by itself can have errors too, and output them only in the terminal (which we don't see when using the extension).

When there is a build error, no notifications appears, and the text of the button don't seem to change too.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/28659185/132950822-722b4aee-a396-4fec-ad4b-b8d307c5cd90.png)

</details>

In jetbrains IDE, we just have to add the build configuration and when we hit the run button, 

<details>
<summary>a console opens like this : 
</summary>

![image](https://blog.jetbrains.com/wp-content/uploads/2017/12/webstorm-vue-npm-start.png)

</details>

I'd like to when I hit the build button, a terminal appears and prints the console output,

<details>
<summary>
like the screenshot below : 
</summary>

![image](https://user-images.githubusercontent.com/28659185/132950722-97eee53f-631f-4324-8467-53556bd40a48.png)

</details>

**Comment by AllanOricil** [comment]
Understood. Yes, that is possible. I will spawn a terminal so you can see the output.

**Comment by AllanOricil** [comment]
@LoganTann I just published 0.0.9 which now uses a Terminal to run the command. Thanks for the idea.
